# Site settings
title: Story Blog
header-img: img/home-bg.jpg
email: relatos@126.com
copyright_name: Story
description: "this is share sotory website!"
baseurl: ""
url: "http://liuyue.ren"
#twitter_username: SBootstrap
github_username:  relatos
#facebook_username:  StartBootstrap
email_username:  relatos@126.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-81503915-2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
